# This is a basic workflow to help you get started with Actions
# This still contains some errors.

name: sample Workflow

# Controls when the workflow will run

# Trigger the workflow when a new issue is opened
on:
  workflow_dispatch:
  issues:
    types: [opened]

permissions:
  id-token: write
  contents: read
#
# Add a job to create a Jira ticket
jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Ticket
        run: |
          curl -X POST "$JIRA_URL/rest/api/2/issue" \
            --user "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data '{
              "fields": {
                "project": { "key": "YOUR_PROJECT_KEY" },
                "summary": "${{ github.event.issue.title }}",
                "description": "${{ github.event.issue.body }}",
                "issuetype": { "name": "Task" },
                "epickey": "ADGTAD-706"
              }
            }'
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
